#!/bin/bash
echo "checking 1"
diff output/1.txt output2/1.txt
echo "checking 2"
diff output/2.txt output2/2.txt
echo "checking 3"
diff output/3.txt output2/3.txt
echo "checking 4"
diff output/4.txt output2/4.txt
echo "checking 5"
diff output/5.txt output2/5.txt
echo "checking 6"
diff output/6.txt output2/6.txt
echo "checking 7"
diff output/7.txt output2/7.txt
echo "checking 8"
diff output/8.txt output2/8.txt
echo "checking 9"
diff output/9.txt output2/9.txt
echo "checking 10"
diff output/10.txt output2/10.txt
echo "checking 11"
diff output/11.txt output2/11.txt
echo "checking 12"
diff output/12.txt output2/12.txt
echo "checking 13"
diff output/13.txt output2/13.txt
echo "checking 14"
diff output/14.txt output2/14.txt
echo "checking 15"
diff output/15.txt output2/15.txt
